version: '3.8'

services:
  user-management-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-management-api
    ports:
      - "80:8080"
    environment:
      # Add environment variables if required
      SPRING_PROFILES_ACTIVE: default
    restart: always
